version: "2"

services:
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - project

  project:
    build: ./services/project
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mysql
    restart: always

  mysql:
    build: ./services/mysql
    ports:
      - "3306:3306"
